# Generated by Django 5.1.6 on 2025-04-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_activitytype_location_alter_booking_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
