# Generated by Django 5.1.6 on 2025-04-14 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_booking_date_location_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='default_image',
            field=models.ImageField(default='default_field.jpg', upload_to='fields/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
