# Generated by Django 5.1.6 on 2025-04-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_field_default_image_alter_testimonial_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='location',
        ),
    ]
