# Generated by Django 5.1.4 on 2025-05-12 04:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_location_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='participants',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.slot'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slot',
            name='available_slots',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='slot',
            name='capacity',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='slot',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitytype',
            index=models.Index(fields=['name'], name='booking_act_name_1de157_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'booking_time'], name='booking_boo_user_id_4e6046_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['slot', 'status'], name='booking_boo_slot_id_1c1df2_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['name', 'location'], name='booking_fie_name_ead9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name', 'city'], name='booking_loc_name_213e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['is_featured'], name='booking_loc_is_feat_ab8e43_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', 'created_at'], name='booking_sea_user_id_0a5622_idx'),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['field', 'date', 'start_time'], name='booking_slo_field_i_49ce6a_idx'),
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['available'], name='booking_slo_availab_71fb6b_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['user', 'created_at'], name='booking_tes_user_id_e095c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('user', 'slot'), name='unique_user_slot_booking'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('field', 'date', 'start_time', 'end_time'), name='unique_slot'),
        ),
    ]
